### ISSUE TITLE
[13.0] install Noviat modules and inherited modules

### ISSUE THREAD

**Issue by yboujraf** [Noviat/noviat-apps#3]
Dear @luc-demeyer 

**Odoo 13 CE**

I have installed Odoo13 CE.
I tried to install the addons from Noviat in custom/addons.

When I try to install the addons on Odoo, most of inherited modules are missing.
I tried to find which modules are missing and I have installed one by one but some modules still missing.

Is there a way to have a clean installation of the Noviat Modules without to look for which module is missing?

Best Regards

**Comment by luc-demeyer** [comment]
We can support you on a T&M basis.
