### ISSUE TITLE
[13.0] COA - PCMN not complete after installation

### ISSUE THREAD

**Issue by yboujraf** [Noviat/noviat-apps#4]
Dear @luc-demeyer 

**Chart of accounts**

When i have installed the chart of account COA, in the PCMN, some class are missing.

- How to get all the class?
- do you have the csv or xls format then I could extract the PCMN I have in my odoo 8 to export it to Odoo13?

Best Regards

**Comment by luc-demeyer** [comment]
Export your chart of accounts from your current system in excel format.
Only fields code & name are required.
Import this and the job is done.
