### ISSUE TITLE
_match_journal, multiple bank journals with the same bank account

### ISSUE THREAD

**Issue by BT-cjimeno** [Noviat/noviat-apps#5]
https://github.com/Noviat/noviat-apps/blob/fcd46786024dd4fef51b6120cc5bd60a2c8edd3c/account_statement_import_helper/wizards/account_statement_import.py#L33

Good morning, I'm facing this problem when trying to process an ebics.file and the _match_journal method is run:

In the line referenced above, I'm getting 2 matches, and therefore it fails and uses the original _match_journal method where the sanitized_account_number includes the "EUR" at the end and a "/" in the middle. This original method fails finding any journal at all.

My point is, in the original _match_journal, they have a search with limit=1 that takes the first match that fulfills the domain, however in account_statement_import_helper it is forced to have exactly one match or it will not pick any of the records that pass the filter.

Link to the original _match_journal:
https://github.com/OCA/bank-statement-import/blob/14.0/account_statement_import/wizard/account_statement_import.py#L232

We tried removing the bank account to one of the bank journals but we get the message:
"You cannot remove the bank account from the journal once set."

Is there any way to fix this? or could the code be changed to pick the first matching journal?
Thanks.

**Comment by BT-cjimeno** [comment]
I forgot to mention, I'm having the issue in Odoo 14.0

**Comment by luc-demeyer** [comment]
@BT-cjimeno 
can you contact me offline via luc.demeyer@noviat.com so that I can have an in-depth look and fix the matching logic without the limit=1 because I rather prefer a failing match than booking statements in the wrong journal (some customers have > 100 financial journals hence limit=1 is not an option for this customer segment).

**Comment by BT-cjimeno** [comment]
This issue was solved in a call, thanks a lot Luc!
